#!/usr/bin/env python3
"""Rebuild ../prototype/index.html from index.template.html + out/packets.json."""
import json, os
BASE = os.path.dirname(os.path.abspath(__file__))
packets = json.load(open(f"{BASE}/out/packets.json"))
rep = json.load(open(f"{BASE}/out/groundedness.json"))
audit = []
for p in packets:
    n = sum(len(c["src"]) for c in p["criteria"])
    audit.append(f"{p['id']} · packet generated · pipeline run {rep['run'][:10]} · groundedness {n}/{n} assertions verified · policy pinned {p['policy'].split(' — ')[0]}")
    if p["rec"] == "ROUTE":
        audit.append(f"{p['id']} · evidence conflict detected → auto ROUTE · MD queue")
real = {"grounded": rep["grounded"], "total": rep["assertions"], "pct": rep["groundedness_pct"], "run": rep["run"][:10]}
foot = (f"Packets on this site were generated by the offline retrieval+LLM pipeline on {rep['run'][:10]} — "
        f"{rep['grounded']}/{rep['assertions']} assertions ({rep['groundedness_pct']}%) verified verbatim against source documents; nothing AI-shown is hand-written.")
h = open(f"{BASE}/../prototype/index.template.html").read()
h = (h.replace("__CASES__", json.dumps(packets)).replace("__AUDIT__", json.dumps(audit))
     .replace("__REAL__", json.dumps(real)).replace("__FOOTNOTE__", foot))
open(f"{BASE}/../prototype/index.html", "w").write(h)
print("built", len(h), "bytes")
